include: package:lints/recommended.yaml

linter:
  rules:
    avoid_print: true
    always_declare_return_types: true
    always_use_package_imports: true
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    prefer_single_quotes: true
    sort_pub_dependencies: true
    unnecessary_statements: true

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
