name: bmkg_open_data
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  http: ^0.13.4
  meta: ^1.7.0
  xml: ^6.1.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
