name: bmkg_open_data
description: Dart library for fetching data from https://data.bmkg.go.id/
version: 1.1.0
repository: https://github.com/SuperPenguin/bmkg_open_data
homepage: https://github.com/SuperPenguin/bmkg_open_data

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.1.0
  meta: ^1.9.1
  xml: ^6.3.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.24.0
