name: bmkg_open_data
description: Dart library for fetching data from https://data.bmkg.go.id/
version: 1.0.1
repository: https://github.com/SuperPenguin/bmkg_open_data
homepage: https://github.com/SuperPenguin/bmkg_open_data

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  http: ^0.13.4
  meta: ^1.7.0
  xml: ^6.1.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
